# Generated by Django 5.0.2 on 2024-04-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
