# Generated by Django 5.0.2 on 2024-04-08 04:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_can_vote',
        ),
        migrations.AlterField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=api.models.generate_unique_room_id, max_length=8, unique=True),
        ),
    ]
