# Generated by Django 5.0.2 on 2024-04-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_room_guest_can_vote_alter_room_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
